AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
  ExtraDetails: true
  TargetRubyVersion: 3.4
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake

require:
  - rubocop-capybara
  - rubocop-i18n
  - rubocop-rspec
  - rubocop-sequel
  - rubocop-thread_safety

inherit_from:
  - bundler.yml
  - capybara.yml
  - capybara_rspec.yml
  - gemspec.yml
  - i18n_gettext.yml
  - layout.yml
  - lint.yml
  - metrics.yml
  - migration.yml
  - naming.yml
  - performance.yml
  - rake.yml
  - rspec.yml
  - security.yml
  - sequel.yml
  - style.yml
  - threadsafety.yml
