---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
  - bin/**/*
  - vendor/**/*
  ExtraDetails: true
  TargetRubyVersion: 3.4
  UseCache: true
inherit_mode:
  merge:
  - Exclude
plugins:
- rubocop-i18n
- rubocop-performance
- rubocop-rake
- rubocop-rspec
require:
- rubocop-capybara
- rubocop-sequel
- rubocop-thread_safety
inherit_from:
- bundler.yml
- capybara.yml
- capybara_rspec.yml
- gemspec.yml
- i18n_gettext.yml
- i18n_railsi18n.yml
- layout.yml
- lint.yml
- metrics.yml
- migration.yml
- naming.yml
- performance.yml
- rspec.yml
- rake.yml
- security.yml
- sequel.yml
- style.yml
- threadsafety.yml
