# https://docs.rubocop.org/rubocop/cops_security.html#securityiomethods
Security/IoMethods:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_security.html#securityopen
Security/Open:
  Enabled: true
