# Department 'Capybara' (7):
# https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaraambiguousclick
Capybara/AmbiguousClick:
  Description: Specify the exact target to click on.
  Enabled: true # was false
  VersionAdded: '2.22'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/AmbiguousClick

# Supports --autocorrect
# https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaraassertstyle
Capybara/AssertStyle:
  Description: Checks for usage of deprecated assert style method.
  Enabled: true # was pending
  VersionAdded: '2.23'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/AssertStyle

# https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaraclicklinkorbuttonstyle
Capybara/ClickLinkOrButtonStyle:
  Description: Checks for methods of button or link clicks.
  Enabled: true # was false
  VersionAdded: '2.19'
  VersionChanged: '2.22'
  EnforcedStyle: link_or_button
  SupportedStyles:
  - link_or_button
  - strict
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/ClickLinkOrButtonStyle

# Supports --autocorrect
# https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybarafindallfirst
Capybara/FindAllFirst:
  Description: Enforces use of `first` instead of `all` with `first` or `[0]`.
  Enabled: true # was pending
  SafeAutoCorrect: false
  VersionAdded: '2.22'
  VersionChanged: '2.23'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/FindAllFirst

# Supports --autocorrect
# https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybararedundantwithinfind
Capybara/RedundantWithinFind:
  Description: Checks for redundant `within find(...)` calls.
  Enabled: true # was pending
  VersionAdded: '2.20'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/RedundantWithinFind

# https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaraspecificactions
Capybara/SpecificActions:
  Description: Checks for there is a more specific actions offered by Capybara.
  Enabled: true # was pending
  VersionAdded: '2.14'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/SpecificActions

# Supports --autocorrect
# https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaraspecificfinders
Capybara/SpecificFinders:
  Description: Checks if there is a more specific finder offered by Capybara.
  Enabled: true # was pending
  VersionAdded: '2.13'
  Reference: https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/SpecificFinders

