# Department 'Gemspec' (10):
# Supports --autocorrect
# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecaddruntimedependency
Gemspec/AddRuntimeDependency:
  Description: Prefer `add_dependency` over `add_runtime_dependency`.
  StyleGuide: "#add_dependency_vs_add_runtime_dependency"
  References:
  - https://github.com/rubygems/rubygems/issues/7799#issuecomment-2192720316
  Enabled: true # was pending
  VersionAdded: '1.65'
  Include:
  - "**/*.gemspec"

# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecattributeassignment
Gemspec/AttributeAssignment:
  Description: Use consistent style for Gemspec attributes assignment.
  Enabled: true # was pending
  VersionAdded: '1.77'
  Include:
  - "**/*.gemspec"

# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdependencyversion
Gemspec/DependencyVersion:
  Description: Requires or forbids specifying gem dependency versions.
  Enabled: true # was false
  VersionAdded: '1.29'
  EnforcedStyle: required
  SupportedStyles:
  - required
  - forbidden
  Include:
  - "**/*.gemspec"
  AllowedGems: []

# Supports --autocorrect
# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdeprecatedattributeassignment
Gemspec/DeprecatedAttributeAssignment:
  Description: Checks that deprecated attribute assignments are not set in a gemspec
    file.
  Enabled: true # was pending
  Severity: warning
  VersionAdded: '1.30'
  VersionChanged: '1.40'
  Include:
  - "**/*.gemspec"

# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdevelopmentdependencies
Gemspec/DevelopmentDependencies:
  Description: Checks that development dependencies are specified in Gemfile rather
    than gemspec.
  Enabled: true # was pending
  VersionAdded: '1.44'
  EnforcedStyle: Gemfile
  SupportedStyles:
  - Gemfile
  - gems.rb
  - gemspec
  AllowedGems: []
  Include:
  - "**/*.gemspec"
  - "**/Gemfile"
  - "**/gems.rb"

# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecduplicatedassignment
Gemspec/DuplicatedAssignment:
  Description: An attribute assignment method calls should be listed only once in a
    gemspec.
  Enabled: true
  Severity: warning
  VersionAdded: '0.52'
  VersionChanged: '1.40'
  Include:
  - "**/*.gemspec"

# Supports --autocorrect
# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecordereddependencies
Gemspec/OrderedDependencies:
  Description: Dependencies in the gemspec should be alphabetically sorted.
  Enabled: true
  VersionAdded: '0.51'
  TreatCommentsAsGroupSeparators: true
  ConsiderPunctuation: false
  Include:
  - "**/*.gemspec"

# Supports --autocorrect
# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecrequiremfa
Gemspec/RequireMFA:
  Description: Checks that the gemspec has metadata to require Multi-Factor Authentication
    from RubyGems.
  Enabled: true # was pending
  Severity: warning
  VersionAdded: '1.23'
  VersionChanged: '1.40'
  References:
  - https://guides.rubygems.org/mfa-requirement-opt-in/
  Include:
  - "**/*.gemspec"

# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecrequiredrubyversion
Gemspec/RequiredRubyVersion:
  Description: Checks that `required_ruby_version` of gemspec is specified and equal
    to `TargetRubyVersion` of .rubocop.yml.
  Enabled: true
  Severity: warning
  VersionAdded: '0.52'
  VersionChanged: '1.40'
  Include:
  - "**/*.gemspec"

# https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecrubyversionglobalsusage
Gemspec/RubyVersionGlobalsUsage:
  Description: Checks usage of RUBY_VERSION in gemspec.
  StyleGuide: "#no-ruby-version-in-the-gemspec"
  Enabled: true
  Severity: warning
  VersionAdded: '0.72'
  VersionChanged: '1.40'
  Include:
  - "**/*.gemspec"

