# Department 'ThreadSafety' (6):
# https://docs.rubocop.org/rubocop-thread_safety/cops_thread_safety.html#threadsafetyclassandmoduleattributes
ThreadSafety/ClassAndModuleAttributes:
  Description: Avoid mutating class and module attributes.
  Enabled: true
  ActiveSupportClassAttributeAllowed: false

# https://docs.rubocop.org/rubocop-thread_safety/cops_thread_safety.html#threadsafetyclassinstancevariable
ThreadSafety/ClassInstanceVariable:
  Description: Avoid class instance variables.
  Enabled: true

# https://docs.rubocop.org/rubocop-thread_safety/cops_thread_safety.html#threadsafetydirchdir
ThreadSafety/DirChdir:
  Description: Avoid using `Dir.chdir` due to its process-wide effect.
  Enabled: true
  AllowCallWithBlock: false

# Supports --autocorrect
# https://docs.rubocop.org/rubocop-thread_safety/cops_thread_safety.html#threadsafetymutableclassinstancevariable
ThreadSafety/MutableClassInstanceVariable:
  Description: Do not assign mutable objects to class instance variables.
  Enabled: true
  EnforcedStyle: literals
  SafeAutoCorrect: false
  SupportedStyles:
  - literals
  - strict

# https://docs.rubocop.org/rubocop-thread_safety/cops_thread_safety.html#threadsafetynewthread
ThreadSafety/NewThread:
  Description: Avoid starting new threads. Let a framework like Sidekiq handle the threads.
  Enabled: true

# https://docs.rubocop.org/rubocop-thread_safety/cops_thread_safety.html#threadsafetyrackmiddlewareinstancevariable
ThreadSafety/RackMiddlewareInstanceVariable:
  Description: Avoid instance variables in Rack middleware.
  Enabled: true
  Include:
  - app/middleware/**/*.rb
  - lib/middleware/**/*.rb
  - app/middlewares/**/*.rb
  - lib/middlewares/**/*.rb
  AllowedIdentifiers: []

